### ISSUE TITLE
Don't add mavenLocal

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/SpongeGradle#16]
I've noticed that this plugin is adding `mavenLocal()` to the reositories (https://github.com/SpongePowered/SpongeGradle/blob/master/src/main/groovy/org/spongepowered/gradle/plugin/SpongePluginPlugin.groovy#L49)  
This is an issue because if maven is being used too, there often is the chance that in mavenLocal the source and javadoc artifacts are missing. Keep in mind that that is where maven caches its downloaded artifacts. Additionally there might be issues with snaptshots, as they aren't updated in mavenLocal.

**Comment by stephan-gh** [comment]
The main problem is that since SpongeGradle adds its repositories first, it's rather ugly to add in `mavenLocal()` as the first repository manually. It's possible, but not pretty.

However, I think I mainly added it because @kashike asked me to do it. See https://github.com/SpongePowered/SpongeGradle/commit/48933f970b00c916e5f960661e9b0cb65ecc0834

**Comment by BrainStone** [comment]
Removing mavenLocal again is just as ugly though.

And since it seems that adding repos through a plugin can be a real hassle, I think it's worth a thought to not add any repos at all.

**Comment by zml2008** [comment]
This issue is no longer applicable to SpongeGradle 2.0.0+
